= Preface

== Purpose

This document describes the architecture of the S2 Episode Information Model.

The intended audience includes Standards bodies producing health informatics standards; solution vendors; health data managers.

== Related Documents

Prerequisite documents for reading this document include:

* The {s2_rm_overview}[S2 Architecture Overview^].

Related documents include:

* The {s2_base_model_support}[S2 Model Support Types^];
* The {s2_base_data_types}[S2 Data Types Information Model^];

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {s2_admin_latest_episode}[{s2_admin_latest_episode}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {s2_specifications_forum}[{product_name} forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Conformance

Conformance of a data or software artifact to an {product_name} specification is determined by a formal test of that artifact against the relevant {product_name} Implementation Technology Specification(s) (ITSs), such as a JSON-schema or OpenAPI specification. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.
